# Generated by Django 5.2.6 on 2026-03-31 16:46

import apps.accounts.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('phone', models.CharField(max_length=32, verbose_name='телефон')),
                ('personal_data_consent', models.BooleanField(default=False, verbose_name='согласие на обработку ПДн')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
            ],
            options={
                'verbose_name': 'заявка агента',
                'verbose_name_plural': 'заявки агентов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, max_length=32, verbose_name='телефон')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='имя и фамилия')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='телефон профиля')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'профиль агента',
                'verbose_name_plural': 'профили агентов',
            },
        ),
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', editable=False, max_length=32, unique=True, verbose_name='код объекта')),
                ('property_type', models.CharField(choices=[('land', 'Земельные участки'), ('house', 'Дом'), ('apartment', 'Квартира'), ('commercial', 'Коммерческая'), ('other', 'Другое')], default='other', max_length=32, verbose_name='тип объекта')),
                ('name', models.CharField(max_length=500, verbose_name='название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='цена, ₽')),
                ('settlement', models.CharField(blank=True, max_length=255, verbose_name='населённый пункт')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='район / адрес')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='площадь, м²')),
                ('floors', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='этажей')),
                ('rooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='комнат')),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='спален')),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='санузлов')),
                ('year_built', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='год постройки')),
                ('wall_material', models.CharField(blank=True, max_length=255, verbose_name='материал стен')),
                ('finishing', models.CharField(blank=True, max_length=255, verbose_name='отделка')),
                ('communications', models.CharField(blank=True, max_length=500, verbose_name='коммуникации')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='теги')),
                ('status', models.CharField(choices=[('moderation', 'На модерации'), ('published', 'Опубликован'), ('rejected', 'Отклонён')], default='moderation', max_length=20, verbose_name='статус')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='причина отклонения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_listings', to=settings.AUTH_USER_MODEL, verbose_name='агент')),
            ],
            options={
                'verbose_name': 'объект недвижимости',
                'verbose_name_plural': 'объекты недвижимости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.accounts.models.property_image_upload_to, verbose_name='изображение')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.propertylisting', verbose_name='объект')),
            ],
            options={
                'verbose_name': 'изображение объекта',
                'verbose_name_plural': 'изображения объектов',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
