# Generated by Django 5.2.6 on 2026-04-01 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_expand_catalog_reference_lists'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompareListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='добавлено')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compared_by_users', to='accounts.propertylisting', verbose_name='объект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compare_listings_links', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'объект в сравнении',
                'verbose_name_plural': 'сравнение',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'listing'), name='unique_user_compare_listing')],
            },
        ),
        migrations.CreateModel(
            name='UserFavoriteListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='добавлено')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_users', to='accounts.propertylisting', verbose_name='объект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_listings_links', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'избранный объект',
                'verbose_name_plural': 'избранное',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'listing'), name='unique_user_favorite_listing')],
            },
        ),
    ]
