# Generated by Django 5.2.6 on 2026-04-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_favorites_and_compare_and_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='distance_to_mkad_km',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='до МКАД, км'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='electricity_supply',
            field=models.CharField(blank=True, max_length=255, verbose_name='электричество'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='has_asphalt_roads',
            field=models.BooleanField(default=False, verbose_name='асфальтированные дороги'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='has_guarded_territory',
            field=models.BooleanField(default=False, verbose_name='охраняемая территория'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='has_street_lighting',
            field=models.BooleanField(default=False, verbose_name='уличное освещение'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='heating_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='отопление'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='internet_connection',
            field=models.CharField(blank=True, max_length=255, verbose_name='интернет'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='land_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Только земля: сотки (1 сотка = 100 м²).', max_digits=12, null=True, verbose_name='площадь участка, сот.'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='широта (WGS84)'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='долгота (WGS84)'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='near_public_transport',
            field=models.BooleanField(default=False, verbose_name='остановка ОТ рядом'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='near_school_kindergarten',
            field=models.BooleanField(default=False, verbose_name='школа и детский сад рядом'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='near_shops',
            field=models.BooleanField(default=False, verbose_name='магазины рядом'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='sewage_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='канализация'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='water_supply',
            field=models.CharField(blank=True, max_length=255, verbose_name='водоснабжение'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Для входа в API должен быть True. При создании кабинета из заявки выставляется автоматически; вручную — для пользователей, заведённых только через админку.', verbose_name='подтверждён администратором'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='address',
            field=models.CharField(blank=True, help_text='Вручную: улица, дом, ориентир.', max_length=500, verbose_name='адрес (улица, дом)'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Жилая / общая площадь постройки; для участка без дома можно не заполнять.', max_digits=12, null=True, verbose_name='площадь дома / объекта, м²'),
        ),
    ]
