# Generated by Django 5.2.6 on 2026-04-08 04:20

import django.db.models.deletion
from django.db import migrations, models


def seed_categories_and_backfill(apps, schema_editor):
    PropertyCategory = apps.get_model('accounts', 'PropertyCategory')
    PropertyListing = apps.get_model('accounts', 'PropertyListing')
    rows = [
        (1, 'Новостройки', 'new_building'),
        (2, 'Загородная недвижимость', 'suburban'),
        (3, 'Земельные участки', 'land_plot'),
        (4, 'Вторичная недвижимость', 'secondary'),
        (5, 'Коммерческая недвижимость', 'commercial'),
        (99, 'Другое', 'other'),
    ]
    slug_to_pk = {}
    for sort_order, name, slug in rows:
        obj, _created = PropertyCategory.objects.get_or_create(
            slug=slug,
            defaults={'name': name, 'sort_order': sort_order},
        )
        slug_to_pk[slug] = obj.pk

    legacy_to_slug = {
        'land': 'land_plot',
        'house': 'suburban',
        'apartment': 'secondary',
        'commercial': 'commercial',
        'other': 'other',
    }
    for row in PropertyListing.objects.iterator():
        slug = legacy_to_slug.get(row.property_type, 'other')
        cid = slug_to_pk.get(slug)
        if cid and row.category_id is None:
            PropertyListing.objects.filter(pk=row.pk).update(category_id=cid)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_propertylisting_detail_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='название')),
                ('slug', models.SlugField(help_text='Латиница без пробелов: new_building, suburban, land_plot…', max_length=64, unique=True, verbose_name='код')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'категория объекта',
                'verbose_name_plural': 'категории объектов',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='property_type',
            field=models.CharField(choices=[('land', 'Земельные участки'), ('house', 'Дом'), ('apartment', 'Квартира'), ('commercial', 'Коммерческая'), ('other', 'Другое')], default='other', help_text='Подстраивается от категории при сохранении; для фильтров API пока сохраняем.', max_length=32, verbose_name='тип объекта (legacy)'),
        ),
        migrations.CreateModel(
            name='LandPlotListingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reference_id', models.CharField(blank=True, help_text='Отображаемый номер для клиента (если нужен).', max_length=64, verbose_name='ID на витрине')),
                ('plot_number', models.CharField(blank=True, max_length=64, verbose_name='№ участка')),
                ('cadastral_number', models.CharField(blank=True, max_length=128, verbose_name='кадастровый номер')),
                ('land_purpose', models.CharField(blank=True, max_length=255, verbose_name='назначение земли')),
                ('contract_form', models.CharField(blank=True, max_length=128, verbose_name='форма договора')),
                ('completion_quarter_text', models.CharField(blank=True, max_length=128, verbose_name='срок сдачи / подключения')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='land_plot_details', to='accounts.propertylisting', verbose_name='объект')),
            ],
            options={
                'verbose_name': 'детали: участок',
                'verbose_name_plural': 'блок «Земельный участок»',
            },
        ),
        migrations.CreateModel(
            name='NewBuildingListingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.CharField(blank=True, max_length=255, verbose_name='застройщик')),
                ('completion_period_text', models.CharField(blank=True, help_text='Например: 3 кв. 2026 — 2 кв. 2028', max_length=255, verbose_name='срок сдачи (текст)')),
                ('housing_class', models.CharField(blank=True, max_length=128, verbose_name='класс жилья')),
                ('house_construction_type', models.CharField(blank=True, max_length=255, verbose_name='тип дома')),
                ('parking_info', models.CharField(blank=True, max_length=255, verbose_name='паркинг')),
                ('registration_settlement', models.CharField(blank=True, max_length=255, verbose_name='регистрация / НП')),
                ('escrow_bank', models.CharField(blank=True, max_length=255, verbose_name='эскроу-счёт (банк)')),
                ('project_finishing', models.CharField(blank=True, max_length=255, verbose_name='отделка (уровень проекта)')),
                ('district_note', models.CharField(blank=True, max_length=255, verbose_name='район (подпись в карточке)')),
                ('units_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='всего квартир / единиц')),
                ('units_available', models.PositiveIntegerField(blank=True, null=True, verbose_name='в продаже')),
                ('price_per_sqm_from', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='цена за м² от, ₽')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='new_building_details', to='accounts.propertylisting', verbose_name='объект')),
            ],
            options={
                'verbose_name': 'детали: новостройка',
                'verbose_name_plural': 'блок «Новостройка»',
            },
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Определяет блок «детали категории» в карточке. Сохраните объект, затем заполните блок.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='accounts.propertycategory', verbose_name='категория витрины'),
        ),
        migrations.CreateModel(
            name='SuburbanListingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.CharField(blank=True, max_length=255, verbose_name='застройщик')),
                ('completion_quarter_text', models.CharField(blank=True, max_length=128, verbose_name='срок сдачи')),
                ('contract_form', models.CharField(blank=True, max_length=128, verbose_name='форма договора')),
                ('payment_methods', models.TextField(blank=True, verbose_name='способы оплаты')),
                ('travel_time_note', models.CharField(blank=True, help_text='Например: До Москвы — 25 мин на автомобиле', max_length=255, verbose_name='подпись про дорогу до города')),
                ('plot_location_text', models.TextField(blank=True, verbose_name='участок и локация (текст)')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suburban_details', to='accounts.propertylisting', verbose_name='объект')),
            ],
            options={
                'verbose_name': 'детали: загород',
                'verbose_name_plural': 'блок «Загород»',
            },
        ),
        migrations.RunPython(seed_categories_and_backfill, noop),
    ]
