# Generated by Django 5.2.6 on 2026-04-08 17:24

import django.db.models.deletion
from django.db import migrations, models


def merge_into_residential_and_seed_categories(apps, schema_editor):
    NewBuilding = apps.get_model('accounts', 'NewBuildingListingDetails')
    Suburban = apps.get_model('accounts', 'SuburbanListingDetails')
    Residential = apps.get_model('accounts', 'ResidentialListingDetails')
    PropertyCategory = apps.get_model('accounts', 'PropertyCategory')

    for nb in NewBuilding.objects.iterator():
        Residential.objects.create(
            listing_id=nb.listing_id,
            developer=nb.developer,
            completion_period_text=nb.completion_period_text,
            housing_class=nb.housing_class,
            house_construction_type=nb.house_construction_type,
            parking_info=nb.parking_info,
            registration_settlement=nb.registration_settlement,
            escrow_bank=nb.escrow_bank,
            project_finishing=nb.project_finishing,
            district_note=nb.district_note,
            units_total=nb.units_total,
            units_available=nb.units_available,
            price_per_sqm_from=nb.price_per_sqm_from,
        )

    for sb in Suburban.objects.iterator():
        existing = Residential.objects.filter(listing_id=sb.listing_id).first()
        cpt = (sb.completion_quarter_text or '')[:255]
        if existing:
            if sb.developer and not existing.developer:
                existing.developer = sb.developer
            if cpt and not existing.completion_period_text:
                existing.completion_period_text = cpt
            if sb.contract_form and not existing.contract_form:
                existing.contract_form = sb.contract_form
            if sb.payment_methods:
                if existing.payment_methods:
                    existing.payment_methods = (
                        f'{existing.payment_methods.strip()}\n{sb.payment_methods.strip()}'.strip()
                    )
                else:
                    existing.payment_methods = sb.payment_methods
            if sb.travel_time_note and not existing.travel_time_note:
                existing.travel_time_note = sb.travel_time_note
            if sb.plot_location_text:
                if existing.plot_location_text:
                    existing.plot_location_text = (
                        f'{existing.plot_location_text.strip()}\n{sb.plot_location_text.strip()}'.strip()
                    )
                else:
                    existing.plot_location_text = sb.plot_location_text
            existing.save()
        else:
            Residential.objects.create(
                listing_id=sb.listing_id,
                developer=sb.developer,
                completion_period_text=cpt,
                contract_form=sb.contract_form,
                payment_methods=sb.payment_methods,
                travel_time_note=sb.travel_time_note,
                plot_location_text=sb.plot_location_text,
            )

    for sort_order, name, slug in [
        (6, 'Коттеджи', 'cottage'),
        (7, 'Дачи', 'dacha'),
    ]:
        PropertyCategory.objects.get_or_create(
            slug=slug,
            defaults={'name': name, 'sort_order': sort_order},
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_property_category_and_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylisting',
            name='category',
            field=models.ForeignKey(
                blank=True,
                help_text='Участок — отдельные поля блока. Остальные категории (новостройки, вторичка, загород, коттеджи, дачи и т.д.) используют общий блок деталей как в макете новостройки.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='listings',
                to='accounts.propertycategory',
                verbose_name='категория витрины',
            ),
        ),
        migrations.CreateModel(
            name='ResidentialListingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.CharField(blank=True, max_length=255, verbose_name='застройщик')),
                ('completion_period_text', models.CharField(blank=True, help_text='Например: 3 кв. 2026 — 2 кв. 2028', max_length=255, verbose_name='срок сдачи (текст)')),
                ('housing_class', models.CharField(blank=True, max_length=128, verbose_name='класс жилья')),
                ('house_construction_type', models.CharField(blank=True, max_length=255, verbose_name='тип дома')),
                ('parking_info', models.CharField(blank=True, max_length=255, verbose_name='паркинг')),
                ('registration_settlement', models.CharField(blank=True, max_length=255, verbose_name='регистрация / НП')),
                ('escrow_bank', models.CharField(blank=True, max_length=255, verbose_name='эскроу-счёт (банк)')),
                ('project_finishing', models.CharField(blank=True, max_length=255, verbose_name='отделка (уровень проекта)')),
                ('district_note', models.CharField(blank=True, max_length=255, verbose_name='район (подпись в карточке)')),
                ('units_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='всего квартир / единиц')),
                ('units_available', models.PositiveIntegerField(blank=True, null=True, verbose_name='в продаже')),
                ('price_per_sqm_from', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='цена за м² от, ₽')),
                ('contract_form', models.CharField(blank=True, max_length=128, verbose_name='форма договора')),
                ('payment_methods', models.TextField(blank=True, verbose_name='способы оплаты')),
                ('travel_time_note', models.CharField(blank=True, help_text='Например: До Москвы — 25 мин на автомобиле', max_length=255, verbose_name='подпись про дорогу до города')),
                ('plot_location_text', models.TextField(blank=True, verbose_name='участок и локация (текст)')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='residential_details', to='accounts.propertylisting', verbose_name='объект')),
            ],
            options={
                'verbose_name': 'детали: жилая (новостройка / вторичка / загород…)',
                'verbose_name_plural': 'блок «Жилая недвижимость»',
            },
        ),
        migrations.RunPython(merge_into_residential_and_seed_categories, noop_reverse),
        migrations.DeleteModel(name='NewBuildingListingDetails'),
        migrations.DeleteModel(name='SuburbanListingDetails'),
    ]
