# Generated by Django 5.2.6 on 2026-04-25

import django.db.models.deletion
from django.db import migrations, models


def seed_main_and_sub_categories(apps, schema_editor):
    PropertyCategory = apps.get_model('accounts', 'PropertyCategory')

    # Main category: Загородная недвижимость
    suburban, _ = PropertyCategory.objects.get_or_create(
        slug='suburban',
        defaults={'name': 'Загородная недвижимость', 'sort_order': 2},
    )
    if suburban.parent_id is not None:
        suburban.parent_id = None
        suburban.save(update_fields=['parent'])

    # Required sub-categories under suburban
    sub_rows = [
        ('land_plot', 'Земельные участки', 1),
        ('dacha', 'Дачи', 2),
        ('cottage', 'Коттеджи', 3),
    ]
    for slug, name, sort_order in sub_rows:
        obj, _ = PropertyCategory.objects.get_or_create(
            slug=slug,
            defaults={'name': name, 'sort_order': sort_order},
        )
        if obj.parent_id != suburban.pk:
            obj.parent_id = suburban.pk
            obj.save(update_fields=['parent'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0011_residential_details_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycategory',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                help_text='Пусто — основная категория; заполнено — подкатегория (sub category).',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subcategories',
                to='accounts.propertycategory',
                verbose_name='родительская категория',
            ),
        ),
        migrations.RunPython(seed_main_and_sub_categories, noop),
    ]

