# Generated by Django 5.2.6 on 2026-04-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_residential_details_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residentiallistingdetails',
            options={'verbose_name': ('детали: жилая (новостройка / вторичка / загород…)',), 'verbose_name_plural': 'блок «Жилая недвижимость»'},
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True, verbose_name='широта (WGS84)'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True, verbose_name='долгота (WGS84)'),
        ),
    ]
