# Generated by Django 5.2.6 on 2026-04-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_residentiallistingdetails_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='is_actual_offer',
            field=models.BooleanField(default=False, help_text='Показ на главной в карусели «Актуальные предложения». Включает администратор.', verbose_name='в блоке «Актуальные предложения»'),
        ),
    ]
