# Generated by Django 5.2.6 on 2026-04-08 18:28

import apps.accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_propertylisting_is_actual_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_label', models.CharField(blank=True, help_text='Одинаковое значение — одна строка аккордеона (например Студия, 1-комнатная).', max_length=64, verbose_name='группа планировки')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='подпись на карточке')),
                ('building', models.CharField(blank=True, max_length=64, verbose_name='корпус')),
                ('completion_text', models.CharField(blank=True, max_length=255, verbose_name='срок сдачи')),
                ('keys_handover_text', models.CharField(blank=True, max_length=255, verbose_name='выдача ключей')),
                ('rooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='комнат')),
                ('is_studio', models.BooleanField(default=False, verbose_name='студия')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='цена, ₽')),
                ('total_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='S общая, м²')),
                ('kitchen_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='S кухни, м²')),
                ('floor', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='этаж')),
                ('floors_total', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='этажей в доме')),
                ('finishing', models.CharField(blank=True, max_length=255, verbose_name='отделка')),
                ('bathroom_summary', models.CharField(blank=True, max_length=255, verbose_name='санузел')),
                ('ceiling_height', models.CharField(blank=True, max_length=64, verbose_name='высота потолков')),
                ('balcony_summary', models.CharField(blank=True, max_length=255, verbose_name='балкон')),
                ('payment_methods', models.CharField(blank=True, max_length=500, verbose_name='способы оплаты')),
                ('banks', models.CharField(blank=True, max_length=500, verbose_name='банки')),
                ('is_apartments_legal', models.BooleanField(default=False, verbose_name='апартаменты')),
                ('is_assignment', models.BooleanField(default=False, verbose_name='переуступка')),
                ('is_two_level', models.BooleanField(default=False, verbose_name='двухуровневая')),
                ('has_master_bedroom', models.BooleanField(default=False, verbose_name='мастер-спальня')),
                ('price_per_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='цена за м², ₽')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.listing_unit_image_upload_to, verbose_name='планировка / фото')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='accounts.propertylisting', verbose_name='объект-ЖК')),
            ],
            options={
                'verbose_name': 'планировка (лот)',
                'verbose_name_plural': 'планировки и цены',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
