# Generated by Django 5.2.6 on 2026-04-13 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_property_listing_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListingRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='причина отклонения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('is_seen', models.BooleanField(default=False, verbose_name='просмотрено агентом')),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='когда просмотрено')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_notices', to='accounts.propertylisting', verbose_name='объект')),
            ],
            options={
                'verbose_name': 'уведомление об отклонении',
                'verbose_name_plural': 'уведомления об отклонении',
                'ordering': ['-created_at'],
            },
        ),
    ]
