# Generated by GPT-5.2 on 2026-04-22

from django.db import migrations, models


def backfill_regions(apps, schema_editor):
    District = apps.get_model('accounts', 'District')
    Highway = apps.get_model('accounts', 'Highway')

    # Все старые записи по умолчанию считаем Москвой.
    District.objects.filter(region__isnull=True).update(region='moscow')
    Highway.objects.filter(region__isnull=True).update(region='moscow')

    # Если в названии явно указан СПб — переносим в Санкт-Петербург.
    District.objects.filter(name__icontains='спб').update(region='saint_petersburg')
    District.objects.filter(name__icontains='санкт').update(region='saint_petersburg')

    # Явный список районов СПб/ЛО из справочника проекта.
    spb_district_names = [
        'Адмиралтейский',
        'Василеостровский',
        'Выборгский',
        'Калининский',
        'Кировский',
        'Колпинский',
        'Красногвардейский',
        'Красносельский (СПб)',
        'Кронштадтский',
        'Курортный',
        'Московский район (СПб)',
        'Невский',
        'Петроградский',
        'Петродворцовый',
        'Приморский',
        'Пушкинский район (СПб)',
        'Фрунзенский',
        'Центральный',
        'Всеволожский',
        'Гатчина',
        'Кингисеппский',
        'Киришский',
        'Лужский',
        'Приозерский',
        'Тосненский',
    ]
    District.objects.filter(name__in=spb_district_names).update(region='saint_petersburg')


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0015_property_listing_rejection'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.CharField(
                choices=[('moscow', 'Москва'), ('saint_petersburg', 'Санкт-Петербург')],
                db_index=True,
                default='moscow',
                help_text='Ограничено двумя регионами витрины: Москва или Санкт-Петербург.',
                max_length=32,
                verbose_name='регион',
            ),
        ),
        migrations.AddField(
            model_name='highway',
            name='region',
            field=models.CharField(
                choices=[('moscow', 'Москва'), ('saint_petersburg', 'Санкт-Петербург')],
                db_index=True,
                default='moscow',
                help_text='Ограничено двумя регионами витрины: Москва или Санкт-Петербург.',
                max_length=32,
                verbose_name='регион',
            ),
        ),
        migrations.RunPython(backfill_regions, migrations.RunPython.noop),
    ]

