# Generated by Django 5.2.6 on 2026-04-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_propertycategory_parent_and_proxies'),
        ('accounts', '0016_district_highway_region'),
    ]

    operations = [
    ]
