# Generated by Django 5.2.6 on 2026-04-25

from django.db import migrations, models
from django.utils.text import slugify

_CYRILLIC_TO_LATIN = {
    'а': 'a',
    'б': 'b',
    'в': 'v',
    'г': 'g',
    'д': 'd',
    'е': 'e',
    'ё': 'e',
    'ж': 'zh',
    'з': 'z',
    'и': 'i',
    'й': 'y',
    'к': 'k',
    'л': 'l',
    'м': 'm',
    'н': 'n',
    'о': 'o',
    'п': 'p',
    'р': 'r',
    'с': 's',
    'т': 't',
    'у': 'u',
    'ф': 'f',
    'х': 'h',
    'ц': 'ts',
    'ч': 'ch',
    'ш': 'sh',
    'щ': 'sch',
    'ъ': '',
    'ы': 'y',
    'ь': '',
    'э': 'e',
    'ю': 'yu',
    'я': 'ya',
}


def _transliterate_ru(text: str) -> str:
    out = []
    for ch in (text or '').lower():
        if ch in _CYRILLIC_TO_LATIN:
            out.append(_CYRILLIC_TO_LATIN[ch])
        else:
            out.append(ch)
    return ''.join(out)


def _slug_base(name: str, code: str = '') -> str:
    base = slugify(_transliterate_ru(name or ''))[:50].strip('-')
    if not base and code:
        base = slugify(_transliterate_ru(code))[:50].strip('-')
    if not base:
        base = 'listing'
    return base


def backfill_listing_slugs(apps, schema_editor):
    PropertyListing = apps.get_model('accounts', 'PropertyListing')
    used = set()

    for obj in PropertyListing.objects.all().order_by('pk'):
        if (obj.slug or '').strip():
            used.add(obj.slug)
            continue
        base = _slug_base(obj.name, obj.code)
        candidate = base
        n = 0
        while candidate in used:
            n += 1
            candidate = f'{base}-{n}'
        obj.slug = candidate
        used.add(candidate)
        obj.save(update_fields=['slug'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0017_merge_20260425_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='slug',
            field=models.SlugField(
                blank=True,
                default='',
                help_text='Для URL витрины: /catalog/{slug}. Генерируется из названия (латиница). Пример: «Аструм» → astrum.',
                max_length=64,
                verbose_name='адрес в каталоге (slug)',
            ),
        ),
        migrations.RunPython(backfill_listing_slugs, noop),
        migrations.AlterField(
            model_name='propertylisting',
            name='slug',
            field=models.SlugField(
                blank=True,
                default='',
                help_text='Для URL витрины: /catalog/{slug}. Генерируется из названия (латиница). Пример: «Аструм» → astrum.',
                max_length=64,
                unique=True,
                verbose_name='адрес в каталоге (slug)',
            ),
        ),
    ]
