# Generated by Django 5.2.6 on 2026-04-26

import django.db.models.deletion
from django.db import migrations, models


def migrate_residential_to_suburban(apps, schema_editor):
    PropertyListing = apps.get_model('accounts', 'PropertyListing')
    PropertyCategory = apps.get_model('accounts', 'PropertyCategory')
    Residential = apps.get_model('accounts', 'ResidentialListingDetails')
    Suburban = apps.get_model('accounts', 'SuburbanListingDetails')

    suburban_cat_ids = set(
        PropertyCategory.objects.filter(slug__in=('dacha', 'cottage')).values_list('pk', flat=True)
    )
    if not suburban_cat_ids:
        return

    house_map = {
        'кирпич': 'brick',
        'газобетон': 'gas_concrete',
        'пеноблок': 'gas_concrete',
        'дерев': 'wood',
        'каркас': 'frame',
        'монолит': 'monolith',
        'комбин': 'combined',
    }

    for listing_id in PropertyListing.objects.filter(category_id__in=suburban_cat_ids).values_list(
        'pk', flat=True
    ):
        res = Residential.objects.filter(listing_id=listing_id).first()
        if not res:
            Suburban.objects.get_or_create(
                listing_id=listing_id,
                defaults={
                    'contract_form': '',
                    'payment_methods': '',
                    'travel_time_note': '',
                    'plot_location_text': '',
                },
            )
            continue
        house_type = ''
        raw_type = (res.house_construction_type or '').lower()
        for key, val in house_map.items():
            if key in raw_type:
                house_type = val
                break
        Suburban.objects.update_or_create(
            listing_id=listing_id,
            defaults={
                'house_type': house_type,
                'external_finishing': '',
                'contract_form': res.contract_form or '',
                'payment_methods': res.payment_methods or '',
                'travel_time_note': res.travel_time_note or '',
                'plot_location_text': res.plot_location_text or '',
            },
        )
        Residential.objects.filter(pk=res.pk).delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0018_propertylisting_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='gas_supply',
            field=models.CharField(blank=True, max_length=255, verbose_name='газ'),
        ),
        migrations.CreateModel(
            name='SuburbanListingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'house_type',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('brick', 'Кирпичный'),
                            ('gas_concrete', 'Газобетон / пеноблок'),
                            ('wood', 'Деревянный'),
                            ('frame', 'Каркасный'),
                            ('monolith', 'Монолитный'),
                            ('combined', 'Комбинированный'),
                        ],
                        max_length=32,
                        verbose_name='тип дома',
                    ),
                ),
                (
                    'external_finishing',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('facade_plaster', 'Фасадная штукатурка'),
                            ('siding_panels', 'Сайдинг и панели'),
                            ('facade_tile', 'Фасадная плитка'),
                            ('brick_stone', 'Кирпич / камень'),
                            ('wood_cladding', 'Облицовка дерево'),
                        ],
                        max_length=32,
                        verbose_name='внешняя отделка',
                    ),
                ),
                ('contract_form', models.CharField(blank=True, max_length=128, verbose_name='форма договора')),
                ('payment_methods', models.TextField(blank=True, verbose_name='способы оплаты')),
                (
                    'travel_time_note',
                    models.CharField(
                        blank=True,
                        help_text='Например: До Москвы — 25 мин на автомобиле',
                        max_length=255,
                        verbose_name='подпись про дорогу до города',
                    ),
                ),
                (
                    'plot_location_text',
                    models.TextField(
                        blank=True,
                        help_text='Дополнение к полям участка, шоссе, МКАД и адресу в карточке объекта.',
                        verbose_name='участок и локация (доп. текст)',
                    ),
                ),
                (
                    'listing',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='suburban_details',
                        to='accounts.propertylisting',
                        verbose_name='объект',
                    ),
                ),
            ],
            options={
                'verbose_name': 'детали: загород (дача / коттедж)',
                'verbose_name_plural': 'блок «Загородная недвижимость»',
            },
        ),
        migrations.RunPython(migrate_residential_to_suburban, noop),
    ]
