# Generated by Django 5.2.6 on 2026-06-18

from django.db import migrations, models


def backfill_listing_regions(apps, schema_editor):
    PropertyListing = apps.get_model('accounts', 'PropertyListing')
    District = apps.get_model('accounts', 'District')
    Highway = apps.get_model('accounts', 'Highway')

    district_regions = dict(District.objects.values_list('pk', 'region'))
    highway_regions = dict(Highway.objects.values_list('pk', 'region'))

    for obj in PropertyListing.objects.all().only('pk', 'district_id', 'highway_id', 'region'):
        region = 'moscow'
        if obj.district_id and obj.district_id in district_regions:
            region = district_regions[obj.district_id] or region
        elif obj.highway_id and obj.highway_id in highway_regions:
            region = highway_regions[obj.highway_id] or region
        if obj.region != region:
            PropertyListing.objects.filter(pk=obj.pk).update(region=region)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0020_repair_listing_slug_and_gas'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='region',
            field=models.CharField(
                choices=[('moscow', 'Москва'), ('saint_petersburg', 'Санкт-Петербург')],
                db_index=True,
                default='moscow',
                help_text='Москва или Санкт-Петербург. На сайте объект показывается только при выборе этого города.',
                max_length=32,
                verbose_name='регион витрины',
            ),
        ),
        migrations.RunPython(backfill_listing_regions, noop),
    ]
