# Generated by Django 5.2.6 on 2026-04-01 04:12

import apps.website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvantageCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('title', models.CharField(max_length=300, verbose_name='заголовок')),
                ('body', models.TextField(verbose_name='текст')),
                ('image', models.ImageField(blank=True, upload_to=apps.website.models.upload_advantage, verbose_name='изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='показывать')),
            ],
            options={
                'verbose_name': 'преимущество',
                'verbose_name_plural': 'преимущества',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, max_length=220, unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=500, verbose_name='заголовок')),
                ('lead', models.CharField(blank=True, max_length=600, verbose_name='подзаголовок / лид')),
                ('image', models.ImageField(upload_to=apps.website.models.upload_article, verbose_name='обложка')),
                ('published_at', models.DateField(verbose_name='дата публикации')),
                ('body', models.TextField(help_text='HTML или обычный текст', verbose_name='текст статьи')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
            ],
            options={
                'verbose_name': 'статья блога',
                'verbose_name_plural': 'статьи блога',
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('author_name', models.CharField(max_length=200, verbose_name='автор')),
                ('city', models.CharField(blank=True, max_length=200, verbose_name='город')),
                ('text', models.TextField(verbose_name='текст отзыва')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
            ],
            options={
                'verbose_name': 'отзыв клиента',
                'verbose_name_plural': 'отзывы клиентов',
                'ordering': ['sort_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('phone', models.CharField(max_length=32, verbose_name='телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('message', models.TextField(blank=True, verbose_name='комментарий')),
                ('personal_data_consent', models.BooleanField(default=False, verbose_name='согласие на обработку ПДн')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
            ],
            options={
                'verbose_name': 'заявка на консультацию',
                'verbose_name_plural': 'заявки на консультацию',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('question', models.CharField(max_length=500, verbose_name='вопрос')),
                ('answer', models.TextField(verbose_name='ответ')),
                ('is_active', models.BooleanField(default=True, verbose_name='показывать')),
            ],
            options={
                'verbose_name': 'вопрос FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=800, verbose_name='подзаголовок')),
                ('image', models.ImageField(upload_to=apps.website.models.upload_hero, verbose_name='изображение')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='показывать')),
            ],
            options={
                'verbose_name': 'слайд главной',
                'verbose_name_plural': 'слайды главной',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('title', models.CharField(max_length=300, verbose_name='заголовок')),
                ('body', models.TextField(verbose_name='описание')),
                ('image', models.ImageField(upload_to=apps.website.models.upload_service, verbose_name='фон / изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='показывать')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=64, verbose_name='телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('address', models.CharField(max_length=500, verbose_name='адрес офиса')),
                ('work_hours', models.CharField(help_text='Напр.: Пн–Пт 9:00–18:00; Сб–Вс — выходной', max_length=300, verbose_name='режим работы')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('vk_url', models.URLField(blank=True, verbose_name='ВКонтакте')),
                ('map_embed_url', models.URLField(blank=True, help_text='Опционально: ссылка на Яндекс.Карты / Google Maps', max_length=800, verbose_name='URL карты (iframe / ссылка)')),
            ],
            options={
                'verbose_name': 'контакты сайта',
                'verbose_name_plural': 'контакты сайта',
            },
        ),
        migrations.CreateModel(
            name='SiteRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='slug')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
            ],
            options={
                'verbose_name': 'регион (город) сайта',
                'verbose_name_plural': 'регионы сайта',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('role', models.CharField(max_length=200, verbose_name='должность')),
                ('experience', models.CharField(blank=True, max_length=300, verbose_name='опыт')),
                ('photo', models.ImageField(upload_to=apps.website.models.upload_team, verbose_name='фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='показывать')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'команда',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
