# Generated by Django 5.2.6 on 2026-04-01 04:24

import apps.website.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecard',
            name='cta_label',
            field=models.CharField(blank=True, default='Оставить заявку', max_length=120, verbose_name='текст кнопки заявки'),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='hero_text',
            field=models.TextField(blank=True, help_text='Основной текст под заголовком на странице услуги (несколько абзацев).', verbose_name='текст героя (страница услуги)'),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='related_services',
            field=models.ManyToManyField(blank=True, related_name='related_from', to='website.servicecard', verbose_name='другие услуги (внизу страницы)'),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='section_features_title',
            field=models.CharField(blank=True, default='Что вы получите', max_length=200, verbose_name='заголовок блока «Что вы получите»'),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='section_workflow_title',
            field=models.CharField(blank=True, default='Как мы работаем', max_length=200, verbose_name='заголовок блока «Как мы работаем»'),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Опционально, для URL; запросы работают по `id`. Несколько пустых значений допустимы только с NULL.', max_length=320, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='body',
            field=models.TextField(help_text='Текст для плитки «Другие услуги» / списка на главной.', verbose_name='краткое описание (карточка)'),
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='image',
            field=models.ImageField(upload_to=apps.website.models.upload_service, verbose_name='изображение (герой / карточка)'),
        ),
        migrations.CreateModel(
            name='ServiceBenefitBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('title', models.CharField(max_length=300, verbose_name='заголовок')),
                ('body', models.TextField(verbose_name='описание')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_blocks', to='website.servicecard', verbose_name='услуга')),
            ],
            options={
                'verbose_name': 'блок выгоды (оранжевая карточка)',
                'verbose_name_plural': 'блоки выгод',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeatureLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('text', models.CharField(max_length=600, verbose_name='пункт списка')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_lines', to='website.servicecard', verbose_name='услуга')),
            ],
            options={
                'verbose_name': 'пункт «Что вы получите»',
                'verbose_name_plural': 'пункты «Что вы получите»',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServicePillTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('text', models.CharField(max_length=200, verbose_name='тег-чип')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pill_tags', to='website.servicecard', verbose_name='услуга')),
            ],
            options={
                'verbose_name': 'чип под блоком преимуществ',
                'verbose_name_plural': 'чипы',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceWorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField(default=1, verbose_name='номер шага')),
                ('title', models.CharField(max_length=300, verbose_name='заголовок шага')),
                ('body', models.TextField(blank=True, verbose_name='подзаголовок / описание')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='website.servicecard', verbose_name='услуга')),
            ],
            options={
                'verbose_name': 'шаг «Как мы работаем»',
                'verbose_name_plural': 'шаги процесса',
                'ordering': ['step_number', 'id'],
            },
        ),
    ]
