# Generated by Django 5.2.6 on 2026-04-01 04:26

from django.db import migrations, models


# Демо-координаты центров (~крупнейшие города РФ). update_or_create по slug.
RUSSIA_SITE_REGIONS_SEED = (
    ('moscow', 'Москва', 0, 55.7558, 37.6176),
    ('saint-petersburg', 'Санкт-Петербург', 1, 59.9343, 30.3351),
    ('novosibirsk', 'Новосибирск', 2, 55.0084, 82.9357),
    ('ekaterinburg', 'Екатеринбург', 3, 56.8431, 60.6454),
    ('kazan', 'Казань', 4, 55.7963, 49.1088),
    ('nizhny-novgorod', 'Нижний Новгород', 5, 56.2965, 43.9361),
    ('chelyabinsk', 'Челябинск', 6, 55.1644, 61.4368),
    ('samara', 'Самара', 7, 53.2001, 50.1500),
    ('omsk', 'Омск', 8, 54.9885, 73.3242),
    ('rostov-on-don', 'Ростов-на-Дону', 9, 47.2357, 39.7015),
    ('ufa', 'Уфа', 10, 54.7388, 55.9721),
    ('krasnoyarsk', 'Красноярск', 11, 56.0184, 92.8672),
    ('voronezh', 'Воронеж', 12, 51.6720, 39.1843),
    ('perm', 'Пермь', 13, 58.0105, 56.2502),
    ('volgograd', 'Волгоград', 14, 48.7080, 44.5133),
    ('krasnodar', 'Краснодар', 15, 45.0355, 38.9753),
    ('saratov', 'Саратов', 16, 51.5336, 46.0342),
    ('tyumen', 'Тюмень', 17, 57.1522, 65.5272),
    ('tolyatti', 'Тольятти', 18, 53.5303, 49.3461),
    ('izhevsk', 'Ижевск', 19, 56.8528, 53.2115),
    ('barnaul', 'Барнаул', 20, 53.3481, 83.7799),
    ('ulyanovsk', 'Ульяновск', 21, 54.3142, 48.4031),
    ('irkutsk', 'Иркутск', 22, 52.2864, 104.2807),
    ('khabarovsk', 'Хабаровск', 23, 48.4827, 135.0840),
    ('yaroslavl', 'Ярославль', 24, 57.6261, 39.8845),
    ('vladivostok', 'Владивосток', 25, 43.1155, 131.8855),
    ('makhachkala', 'Махачкала', 26, 42.9831, 47.5047),
    ('tomsk', 'Томск', 27, 56.4846, 84.9476),
    ('orenburg', 'Оренбург', 28, 51.7682, 55.0970),
    ('kemerovo', 'Кемерово', 29, 55.3331, 86.0835),
    ('novokuznetsk', 'Новокузнецк', 30, 53.7596, 87.1216),
    ('ryazan', 'Рязань', 31, 54.6269, 39.6916),
    ('kaliningrad', 'Калининград', 32, 54.7104, 20.4522),
    ('astrakhan', 'Астрахань', 33, 46.3497, 48.0408),
    ('penza', 'Пенза', 34, 53.2007, 45.0046),
    ('lipetsk', 'Липецк', 35, 52.6031, 39.5708),
    ('kirov', 'Киров', 36, 58.6036, 49.6680),
    ('cheboksary', 'Чебоксары', 37, 56.1439, 47.2489),
    ('tula', 'Тула', 38, 54.1931, 37.6174),
    ('sochi', 'Сочи', 39, 43.5855, 39.7231),
    ('naberezhnye-chelny', 'Набережные Челны', 40, 55.7436, 52.3958),
    ('orel', 'Орёл', 41, 52.9703, 36.0634),
    ('smolensk', 'Смоленск', 42, 54.7826, 32.0451),
    ('sterlitamak', 'Стерлитамак', 43, 53.6306, 55.9317),
    ('magnitogorsk', 'Магнитогорск', 44, 53.4186, 59.0472),
    ('arkhangelsk', 'Архангельск', 45, 64.5393, 40.5173),
    ('belgorod', 'Белгород', 46, 50.5953, 36.5873),
    ('vladimir', 'Владимир', 47, 56.1290, 40.4060),
    ('murmansk', 'Мурманск', 48, 68.9585, 33.0827),
    ('tver', 'Тверь', 49, 56.8587, 35.9176),
    ('sevastopol', 'Севастополь', 50, 44.6166, 33.5254),
    ('simferopol', 'Симферополь', 51, 44.9521, 34.1024),
)


def seed_russia_site_regions(apps, schema_editor):
    SiteRegion = apps.get_model('website', 'SiteRegion')
    for slug, name, sort_order, lat, lon in RUSSIA_SITE_REGIONS_SEED:
        SiteRegion.objects.update_or_create(
            slug=slug,
            defaults={
                'name': name,
                'sort_order': sort_order,
                'is_active': True,
                'latitude': lat,
                'longitude': lon,
            },
        )


def seed_russia_site_regions_reverse(apps, schema_editor):
    SiteRegion = apps.get_model('website', 'SiteRegion')
    slugs = {row[0] for row in RUSSIA_SITE_REGIONS_SEED}
    SiteRegion.objects.filter(slug__in=slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_service_detail_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteregion',
            name='latitude',
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text='Для подбора ближайшего региона по координатам клиента.',
                max_digits=9,
                null=True,
                verbose_name='широта (WGS84)',
            ),
        ),
        migrations.AddField(
            model_name='siteregion',
            name='longitude',
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text='Вместе с широтой — для API геолокации.',
                max_digits=9,
                null=True,
                verbose_name='долгота (WGS84)',
            ),
        ),
        migrations.RunPython(seed_russia_site_regions, seed_russia_site_regions_reverse),
    ]
