# Generated by Django 5.2.6 on 2026-04-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_siteregion_geo_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, help_text='Анонс для карточек, meta/snippet; отличается от короткого лида под заголовком.', verbose_name='краткое описание'),
        ),
        migrations.AddField(
            model_name='article',
            name='sections',
            field=models.JSONField(blank=True, default=list, help_text='Массив объектов: title, intro, list_title, items[], closing. См. подсказку в админке / apps.website.article_sections.', verbose_name='блоки статьи (JSON)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(blank=True, help_text='Старый формат одного поля; для новых статей используйте sections.', verbose_name='legacy: текст/HTML целиком'),
        ),
    ]
