# Generated by Django 5.2.6 on 2026-04-01 04:46

import django.db.models.deletion
from django.db import migrations, models


def migrate_sections_json_to_models(apps, schema_editor):
    Article = apps.get_model('website', 'Article')
    ArticleSection = apps.get_model('website', 'ArticleSection')
    ArticleSectionItem = apps.get_model('website', 'ArticleSectionItem')
    for article in Article.objects.all():
        raw = article.sections
        if raw is None:
            continue
        if not isinstance(raw, list):
            continue
        for order, block in enumerate(raw):
            if not isinstance(block, dict):
                continue
            title = block.get('title') or ''
            sec = ArticleSection.objects.create(
                article_id=article.pk,
                sort_order=order,
                title=str(title)[:500],
                intro=str(block.get('intro') or ''),
                list_title=str(block.get('list_title') or '')[:500],
                closing=str(block.get('closing') or ''),
            )
            items = block.get('items') or []
            if not isinstance(items, list):
                continue
            for j, it in enumerate(items):
                if not isinstance(it, str):
                    continue
                ArticleSectionItem.objects.create(
                    section_id=sec.pk,
                    sort_order=j,
                    text=it[:1000],
                )


def restore_sections_model_to_json(apps, schema_editor):
    Article = apps.get_model('website', 'Article')
    ArticleSection = apps.get_model('website', 'ArticleSection')
    ArticleSectionItem = apps.get_model('website', 'ArticleSectionItem')
    for article in Article.objects.all():
        blocks = []
        for sec in ArticleSection.objects.filter(article_id=article.pk).order_by('sort_order', 'id'):
            items = list(
                ArticleSectionItem.objects.filter(section_id=sec.pk)
                .order_by('sort_order', 'id')
                .values_list('text', flat=True)
            )
            blocks.append(
                {
                    'title': sec.title,
                    'intro': sec.intro,
                    'list_title': sec.list_title,
                    'items': items,
                    'closing': sec.closing,
                }
            )
        article.sections = blocks
        article.save(update_fields=['sections'])


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_article_description_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок блока')),
                ('title', models.CharField(max_length=500, verbose_name='заголовок блока')),
                ('intro', models.TextField(blank=True, verbose_name='вводный текст')),
                ('list_title', models.CharField(blank=True, max_length=500, verbose_name='заголовок списка')),
                ('closing', models.TextField(blank=True, verbose_name='текст после списка')),
                (
                    'article',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='content_sections',
                        to='website.article',
                        verbose_name='статья',
                    ),
                ),
            ],
            options={
                'verbose_name': 'блок статьи',
                'verbose_name_plural': 'блоки статьи',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ArticleSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок пункта')),
                ('text', models.CharField(max_length=1000, verbose_name='текст пункта списка')),
                (
                    'section',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='list_items',
                        to='website.articlesection',
                        verbose_name='блок',
                    ),
                ),
            ],
            options={
                'verbose_name': 'пункт списка',
                'verbose_name_plural': 'пункты списка',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RunPython(migrate_sections_json_to_models, restore_sections_model_to_json),
        migrations.RemoveField(
            model_name='article',
            name='sections',
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(
                blank=True,
                help_text='Старый формат одного поля; для новых статей используйте блоки ниже (inline в админке).',
                verbose_name='legacy: текст/HTML целиком',
            ),
        ),
    ]
