# Generated by Django 5.2.6 on 2026-04-16 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_article_content_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='site_region',
            field=models.ForeignKey(
                blank=True,
                help_text='Опционально: если указан, слайд показывается только для этого региона.',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='hero_slides',
                to='website.siteregion',
                verbose_name='регион (город)',
            ),
        ),
    ]

